version: '3.8'

services:
  https-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: https-proxy:latest
    container_name: https-proxy
    restart: unless-stopped
    ports:
      - "8443:8443"  # HTTPS Proxy port
      - "8444:8444"  # Admin panel port
    volumes:
      - ./certs:/app/certs
      - ./stats:/app/stats
      - ./config.json:/app/config.json
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "-", "https://localhost:8443" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  proxy-network:
    driver: bridge 